# Generated by Django 5.2.7 on 2025-10-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('categoria', models.CharField(max_length=35)),
                ('stock', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('imagen', models.CharField(max_length=200)),
            ],
        ),
    ]
